In [28]:
names_of_employees = ["Harry", "Mike", "Jessie", "Tom", "Mary", "Ruther", "Chervy", "Miller", "Henry", "Ron", "Schaefer", "Hess", "Rich", "Valenzuela", "Moyer", "Morgan", "Bridges", "Buckley", "Bradford", "Gallegos", "Crosby", "Lloyd", "Fleming", "Warner", "Li", "Ashley", "Curry", "Blanchard", "Brooks", "Valentine", "Donovan", "Ford", "Duarte", "Stout", "Gaines", "Flynn", "Kim", "Stein", "Freeman", "Oconnor", "Potts", "Hogan", "Conway", "Serrano", "Charles", "Jennings", "Cox", "Caldwell", "Webster", "Clarke", "Conley", "Schmitt", "Mccoy", "Booker", "York", "Esparza", "Day", "Warren", "Lawson", "Ritter", "Bright", "Rice", "Best", "Gilbert", "Sims", "Meadows", "Krueger", "Carr", "Klein", "Mcgrath", "Donaldson", "Hebert", "Bruce"]
names_of_states = [ "Alabama",
     "Alaska", "American Samoa", "Arizona", "Arkansas","California", "Colorado",
     "Connecticut",
     "Delaware",
     "District Of Columbia",
     "Federated States Of Micronesia",
     "Florida",
     "Georgia",
     "Guam",
     "Hawaii",
     "Idaho",
    "Illinois",
     "Indiana",
     "Iowa",
     "Kansas",
     "Kentucky",
     "Louisiana",
     "Maine",
     "Marshall Islands",
     "Maryland",
     "Massachusetts",
     "Michigan",
     "Minnesota",
     "Mississippi",
     "Missouri",
     "Montana",
     "Nebraska",
     "Nevada",
     "New Hampshire",
     "New Jersey",
     "New Mexico",
     "New York",
     "North Carolina",
     "North Dakota",
     "Northern Mariana Islands",
     "Ohio",
     "Oklahoma",
     "Oregon",
     "Palau",
     "Pennsylvania",
     "Puerto Rico",
     "Rhode Island",
     "South Carolina",
    "South Dakota",
     "Tennessee",
     "Texas",
     "Utah",
     "Vermont",
     "Virgin Islands",
     "Virginia",
     "Washington",
     "West Virginia",
     "Wisconsin",
     "Wyoming"]
food_list = ["chicken", "potatoes", "shrimp", "fish","tomatoes", "apple", "apricot",
        "avocado",
        "banana",
        "bell pepper",
        "bilberry",
        "blackberry",
        "blackcurrant",
        "blood orange",
        "blueberry",
        "boysenberry",
        "breadfruit",
        "canary melon",
        "cantaloupe",
        "cherimoya",
        "cherry",
        "chili pepper",
        "clementine",
        "cloudberry",
        "coconut",
        "cranberry",
        "cucumber",
        "currant",
        "damson",
        "date",
        "dragonfruit",
        "durian",
        "eggplant",
        "elderberry",
        "feijoa",
        "fig",
        "goji berry",
        "gooseberry",
        "grape",
        "grapefruit",
        "guava",
        "honeydew",
        "huckleberry",
        "jackfruit",
        "jambul",
        "jujube",
        "kiwi fruit",
        "kumquat",
        "lemon",
        "lime",
        "loquat",
        "lychee",
        "mandarine",
        "mango",
        "mulberry",
        "nectarine",
        "nut",
        "olive",
        "orange",
        "pamelo",
        "papaya",
        "passionfruit",
        "peach",
        "pear",
        "persimmon",
        "physalis",
        "pineapple",
        "plum",
        "pomegranate",
        "pomelo",
        "purple mangosteen",
        "quince",
        "raisin",
        "rambutan",
        "raspberry",
        "redcurrant",
        "rock melon",
        "salal berry",
        "satsuma",
        "star fruit",
        "strawberry",
        "tamarillo",
        "tangerine",
        "tomato",
        "ugli fruit",
        "watermelon"]

In [29]:
from random import randint
import random
import pandas as pd

In [30]:
list_of_jsonObjects = []


def replace_parameters(template,parameters):
    for i in parameters:
        k = template.find("$",0,len(template))
        if k!=-1: 
            template = template[:k]+i+template[k+2:]
    return template

In [31]:
data = pd.read_excel('input.xlsx', index_col=None, dtype={'Heavy': str,'Light':str},sheet_name='template_13')  
df = pd.DataFrame(data,columns=['Heavy','Light'])
print(df)
template_13 = "Which animal is heavier? $1 or $2 ?"

i=0
while i<100:
    d = {}
            
    # parameters
    list_A = df['Heavy'].tolist()
    list_B = df['Light'].tolist()
    
    obj_A = random.choice(list_A)
    obj_B = random.choice(list_B)
   
        
    parameters = [str(obj_A),str(obj_B)]
    
    #questions
    d["question"] = replace_parameters(template_13,parameters)    
   
    # answer
    ans = obj_A
    option_2 = obj_B

      
    #options
    options_list = [ans, option_2,"both are of equal weight"]
    random.shuffle(options_list)
    
    d["options"] = options_list 
    d["answer"] = ans
    
    list_of_jsonObjects.append(d)

    
    i+=1;

                         Heavy                        Light
0                   Blue Whale      Dwarf Three-Toed Jerboa
1                  Whale Shark        Long-Tailed Planigale
2             African Elephant              Bee Hummingbird
3           White rhinoceros\t             Paedocypris Fish
4                 Hippopotamus                      Vaquita
5                      Giraffe       Spruce-fir Moss Spider
6                    Crocodile             Thorius Arboreus
7                 Asian gaur\t            Pygmy Mouse Lemur
8                        Bison   Paedophryne Amauensis Frog
9            Indian Elephant\t   Speckled Padloper Tortoise
10               Kodiak bear\t           Hippocampus Denise
11                         Yak                Bumblebee Bat
12               Giant Eland\t               Royal Antelope
13             Alaskan Moose\t               Etruscan Shrew
14   North Pacific right whale          Dwarf Lantern Shark
15                   Fin whale      Sphaerodactylus Ariasae
16               Bowhead whale    Brookesia Micra Chameleon
17  North Atlantic right whale               Pygmy Marmoset
18        Southern right whale                 Pygmy Rabbit
19                 Sperm whale                    Chihuahua
20              Humpback whale         Leptotyphlops carlae
21                   Sei whale           Philippine Tarsier
22                  Gray whale        Kitti’s Hog-Nosed Bat
23       African bush elephant     Baluchistan Pygmy Jerboa
24     African forest elephant  Madame Berthe’s Mouse Lemur
25              Asian elephant         Barbados Threadsnake
26           Indian rhinoceros          Slender Blind Snake
27            Black rhinoceros        Williams’ Dwarf Gecko
28            Javan rhinoceros              Brookesia Micra
29              Common ostrich              Bee Hummingbird
30              Somali ostrich  Virgin Island Dwarf Sphaero
31               Elephant seal          Monte Iberia Eleuth
32         Saltwater crocodile                  Paedocypris
33              Green anaconda                          rat
34                    Capybara                       lizard
35                 Kodiak Bear                          dog
36                  Asian Guar                          cat
37                Cape buffalo                          NaN
38              American bison                          NaN

In [32]:
data = pd.read_excel('input.xlsx', index_col=None, dtype={'LargeObjects': str,'TinyObjects':str},sheet_name='template_16')  
df = pd.DataFrame(data,columns=['LargeObjects','TinyObjects'])
print(df)
template_16 = "Given a container of 10 kg volume, which object can be filled in more quantity? $1 or $2 ?"

i=0
while i<10:
    d = {}
            
    # parameters
    list_A = df['LargeObjects'].tolist()
    list_B = df['TinyObjects'].tolist()
    
    obj_A = random.choice(list_A)
    obj_B = random.choice(list_B)
   
        
    parameters = [str(obj_A),str(obj_B)]
    
    #questions
    d["question"] = replace_parameters(template_16,parameters)    
   
    # answer
    ans = obj_B
      
    #options
    options_list = [ans, obj_A,"both the objects can be filled in equal quantity "]
    random.shuffle(options_list)
    
    d["options"] = options_list 
    d["answer"] = ans
    
    list_of_jsonObjects.append(d)

    
    i+=1;

          LargeObjects       TinyObjects
0         basket balls       breadcrumbs
1             balloons           feather
2               bricks             paper
3    5 litre milk cans         ATM cards
4          watermelons              foam
5             pumpkins  polythene covers
6           jackfruits         ear plugs
7            backpacks       safety pins
8           shoe boxes             socks
9   fluffy teddy bears           flowers
10             cookers       puffed rice
11             juicers     chilli flakes
12             bottles            pepper
13            tumblers              salt
14             kettles            powder
15                pots             sugar
16       thermos flask   popsicle sticks
17                 NaN   thermocol balls
18                 NaN       tree leaves
19                 NaN              keys
20                 NaN           pencils
21                 NaN           tablets
22                 NaN             nails
23                 NaN         wall pins
24                 NaN       paper clips
25                 NaN           crayons
26                 NaN       glue sticks
27                 NaN        stem barks
28                 NaN            shells
29                 NaN    small diamonds
30                 NaN         hairbands
31                 NaN        bobby pins
32                 NaN    visiting cards
33                 NaN         lollipops
34                 NaN           ribbons
35                 NaN        gift wraps
36                 NaN           candies
37                 NaN            pearls

In [33]:
data = pd.read_excel('input.xlsx', index_col=None, dtype={'Big': str,'Small':str},sheet_name='template_15')  
df = pd.DataFrame(data,columns=['Big','Small'])
print(df)
template_15 = "$1 can fill the pond faster than $2. true or false "

i=0
while i<100:
    d = {}
            
    # parameters
    list_A = df['Big'].tolist()
    list_B = df['Small'].tolist()
    
    obj_A = random.choice(list_A)
    obj_B = random.choice(list_B)
   
        
    parameters = [str(obj_A),str(obj_B)]
    
    #questions
    d["question"] = replace_parameters(template_15,parameters)    
   
    # answer
    ans = "true"
      
    #options
    options_list = [ans, "false","both can fill the pond faster", "none of them can fill the pond faster"]
    random.shuffle(options_list)
    
    d["options"] = options_list 
    d["answer"] = ans
    
    list_of_jsonObjects.append(d)

    
    i+=1;

    Big  Small
0   NaN    NaN
1   NaN    NaN
2   NaN    NaN
3   NaN    NaN
4   NaN    NaN
5   NaN    NaN
6   NaN    NaN
7   NaN    NaN
8   NaN    NaN
9   NaN    NaN
10  NaN    NaN
11  NaN    NaN
12  NaN    NaN
13  NaN    NaN
14  NaN    NaN
15  NaN    NaN
16  NaN    NaN
17  NaN    NaN
18  NaN    NaN
19  NaN    NaN
20  NaN    NaN
21  NaN    NaN
22  NaN    NaN
23  NaN    NaN
24  NaN    NaN
25  NaN    NaN
26  NaN    NaN
27  NaN    NaN
28  NaN    NaN
29  NaN    NaN
30  NaN    NaN
31  NaN    NaN
32  NaN    NaN
33  NaN    NaN
34  NaN    NaN
35  NaN    NaN
36  NaN    NaN
37  NaN    NaN
38  NaN    NaN
39  NaN    NaN
40  NaN    NaN
41  NaN    NaN
42  NaN    NaN
43  NaN    NaN
44  NaN    NaN
45  NaN    NaN
46  NaN    NaN

NameError: name 'false' is not defined

In [ ]:
template_8 = "$1 bought a phone which costed $2 dollars. Life of a phone battery is $3 hours. On using it daily 24/7 , how many days does the battery last?"
i = 5
while i>0:
    d = {}
    price = randint(5000,10000)
    names= random.choice(names_of_employees)
    battery_life = randint(500,1000)
        
    num_of_days = battery_life/24
    
    d["answer"] = int(num_of_days)
 

    battery_life= str(battery_life)
    price= str(price)

    
    parameters = [names,price,battery_life]
    d["question"] = replace_parameters(template_8, parameters)
    d["options"] = [2, int(num_of_days), int(num_of_days)*2, 0]
    
    list_of_jsonObjects.append(d)
    
    i -= 1

In [ ]:
data = pd.read_excel('input.xlsx', index_col=None, dtype={'Heavy': str,'Light':str},sheet_name='template_15')  
df = pd.DataFrame(data,columns=['Heavy','Light'])
print(df)
template_15 = "You are given 1 kg of $1 and 1 kg of $2 . Which is heavier?"

i=0
while i<100:
    d = {}
            
    # parameters
    list_A = df['Heavy'].tolist()
    list_B = df['Light'].tolist()
    
    obj_A = random.choice(list_A)
    obj_B = random.choice(list_B)
   
        
    parameters = [str(obj_A),str(obj_B)]
    
    #questions
    d["question"] = replace_parameters(template_15,parameters)    
   
      
    #options
    options_list = [obj_A, obj_B,"both are of equal weight"]
    random.shuffle(options_list)
    
    d["options"] = options_list 
    d["answer"] = "both are of equal weight"
    
    list_of_jsonObjects.append(d)

    
    i+=1;

In [ ]:
template_3 = "$1 has Rs $2 with him. He wants to buy $3. One kg of $4 costs Rs $5. How many kgs of $6 can he buy?"
i = 5
while i>0:
    d = {}
    names = random.choice(names_of_employees)
    num_of_kgs = randint(1,50)
    price = randint(15,50)
    amount = randint(0,50)
    food_items = random.choice(food_list)
    
    answer = amount/price
    d["answer"] = amount/price
    
    num_of_kgs= str(num_of_kgs)
    price = str(price)
    amount = str(amount)

    
    parameters = [names,amount,food_items, food_items, price,food_items]
    d["question"] = replace_parameters(template_3, parameters)
    d["options"] = [answer, answer*2, answer*3,1000]
    
    list_of_jsonObjects.append(d)
    
    i -= 1

In [ ]:
template_6 = "$1 's father has taken a loan for farming and has to pay $2 every month to repay the loan. He looks after $3 hens of his village for which he will be paid $4 for each per day. Now he earns $5*$6*30 per month. Does he earn enough amount every month that helps him repay the loan?"
i = 5
while i>0:
    d = {}
    to_pay = randint(5000,10000)
    names= random.choice(names_of_employees)
    num_of_hens = randint(10,40)
    payperhen_perday = randint(1,10)
        
    amount = num_of_hens*payperhen_perday*30
    if amount >= to_pay : d["answer"] = "YES" 
    else :  d["answer"] = "NO"  

    to_pay= str(to_pay)
    num_of_hens = str(num_of_hens)
    payperhen_perday = str(payperhen_perday)

    
    parameters = [names,to_pay,num_of_hens,payperhen_perday, num_of_hens, payperhen_perday]
    d["question"] = replace_parameters(template_6, parameters)
    d["options"] = ["YES", "NO"]
    
    list_of_jsonObjects.append(d)
    
    i -= 1

In [ ]:
template_7 = "$1 took a debt from his relative to buy a phone for Rs $2. He is expected to pay it back in equal amounts every month for $3 months. How much amount does he have to pay per month?"
i = 5
while i>0:
    d = {}
    to_pay = randint(5000,10000)
    names= random.choice(names_of_employees)
    num_of_months = randint(1,12)
        
    topay_permonth = to_pay/num_of_months
    
    d["answer"] = topay_permonth
 

    to_pay= str(to_pay)
    num_of_months= str(num_of_months)

    
    parameters = [names,to_pay,num_of_months]
    d["question"] = replace_parameters(template_7, parameters)
    d["options"] = [30000, topay_permonth, topay_permonth*2, 0]
    
    list_of_jsonObjects.append(d)
    
    i -= 1

In [ ]:
template_10 = "Government is helping farmers buy a cow by paying $1 dollars of its actual cost which is $2 dollars. If the farmers in the state bought around $3 cows. How much did the farmers save on the cows?"
i = 5
while i>0:
    d = {}
    govt_payment = randint(100,500)
    actual_cost = randint(600,1000)
    num_of_cows = randint(20,70)
        
      
    answer = govt_payment*num_of_cows
    
    d["answer"] = int(answer)
 

    govt_payment= str(govt_payment)
    actual_cost= str(actual_cost)
    num_of_cows= str(num_of_cows)

    
    parameters = [govt_payment,actual_cost,num_of_cows]
    d["question"] = replace_parameters(template_10, parameters)
    d["options"] = [2, int(answer), int(answer)*2, 0]
    
    list_of_jsonObjects.append(d)
    
    i -= 1

In [ ]:
import json 
with open('data.json','w',encoding = 'utf-8') as f:
    json.dump(list_of_jsonObjects,f,ensure_ascii=False,indent = 4)